### ISSUE TITLE
No longer depends on expat-sys?

### ISSUE THREAD

**Issue by mssun** [servo/libfontconfig#32]
I found that [expat-sys](https://github.com/servo/libexpat/) didn't public any functions and fontconfig-sys didn't call anything in expat-sys. Is expat-sys still a dependency?

**Comment by jdm** [comment]
libfontconfig depends on libexpat for code like https://github.com/servo/libfontconfig/blob/510fd6ebfe0e547a83ac4b50d3b5e593fb31b04a/src/fcxml.c#L451 . Since it is needed to be linked in the final executable, the Rust crate needs to declare it as a dependency as well.

**Comment by mssun** [comment]
Thanks for the clarification.
