### ISSUE TITLE
Provide an option to disable fallback to self-complied fontconfig and error out

### ISSUE THREAD

**Issue by kchibisov** [servo/libfontconfig#55]
It was discovered multiple times that self-built fontconfig results on very long startup times and a bit broken rendering(due to missing config files on a system ofc). So the end application isn't that much usable and the bugreports from such builds are hard to debug.

So adding a feature flag to disable such fallback could make sense, since users on Linux/BSD don't really want embed fontconfig anyway. However I wonder:

Servo uses fontconfig on android, how do they deal with the startup time error(that it fails to load config). Do they use an embedded config?

**Comment by jdm** [comment]
I suspect the answer lies in https://github.com/servo/servo/blob/master/components/gfx/platform/freetype/android/font_list.rs#L14-L19.

**Comment by kchibisov** [comment]
So, from what I see on fontconfig backend in servo, you should also suffer from static self-build fontconfig as well, since the code is very similar to the one we're using in alacritty. Does the proposed option makes sense or you know for sure how to make all that work *nicely*.

**Comment by jdm** [comment]
A feature to opt out of building libfontconfig sounds fine.
